###
GET http://localhost:8087/health

###
POST http://localhost:8087/test/insert

{"key":"test_key", "value":"test_value"}

###
POST http://localhost:8087/test/update

{"key":"test_key", "value":"test_value_update"}

###
GET http://localhost:8087/test/274

###
GET http://localhost:8087/test/index/test_key
